# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Agent used to exercise streamed function-call arguments."""

from __future__ import annotations

import os
from pathlib import Path

from google.adk import Agent
from google.adk.models.base_llm import BaseLlm
from pydantic import BaseModel
from pydantic import Field


class DocumentSection(BaseModel):
  """A section in the document generated by the tool."""

  heading: str
  purpose: str
  key_points: list[str]
  body: str
  references: list[str] = Field(default_factory=list)


class DocumentRequest(BaseModel):
  """Structured input deliberately large enough to make streaming visible."""

  filename: str
  title: str
  executive_summary: str
  audience: str
  language: str
  tone: str
  keywords: list[str]
  sections: list[DocumentSection]
  include_table_of_contents: bool = True
  footer: str = "Generated by the ADK streaming function-call sample."


def _output_directory() -> Path:
  configured_directory = Path(
      os.getenv("DOCUMENT_OUTPUT_DIR", "generated_docs")
  )
  if not configured_directory.is_absolute():
    configured_directory = Path(__file__).parent / configured_directory
  configured_directory.mkdir(parents=True, exist_ok=True)
  return configured_directory


def create_document(document: DocumentRequest) -> dict[str, str | int]:
  """Create a Markdown document from a structured request.

  Args:
    document: A complete document specification. Include several sections and
      detailed key points so the model has a sizable function-call payload to
      stream.

  Returns:
    The path and basic metadata for the generated Markdown file.
  """
  filename = Path(document.filename).name
  if not filename or filename in {".", ".."}:
    filename = "generated_document.md"
  if not filename.lower().endswith(".md"):
    filename += ".md"

  lines = [
      f"# {document.title}",
      "",
      f"**Audience:** {document.audience}",
      f"**Language:** {document.language}",
      f"**Tone:** {document.tone}",
      "",
      "## Executive Summary",
      "",
      document.executive_summary,
      "",
  ]

  if document.keywords:
    lines.extend(["**Keywords:** " + ", ".join(document.keywords), ""])

  if document.include_table_of_contents:
    lines.extend(["## Table of Contents", ""])
    lines.extend(f"- {section.heading}" for section in document.sections)
    lines.append("")

  for section in document.sections:
    lines.extend([
        f"## {section.heading}",
        "",
        f"**Purpose:** {section.purpose}",
        "",
        section.body,
        "",
        "### Key Points",
        "",
    ])
    lines.extend(f"- {point}" for point in section.key_points)
    if section.references:
      lines.extend(["", "### References", ""])
      lines.extend(f"- {reference}" for reference in section.references)
    lines.append("")

  lines.extend(["---", "", document.footer, ""])
  output_path = _output_directory() / filename
  output_path.write_text("\n".join(lines), encoding="utf-8")
  return {
      "status": "created",
      "path": str(output_path),
      "section_count": len(document.sections),
      "byte_count": output_path.stat().st_size,
  }


def _required_env(name: str) -> str:
  value = os.getenv(name)
  if not value:
    raise RuntimeError(
        f"Set {name} before starting the sample. See README.md for setup."
    )
  return value


def _build_model() -> BaseLlm:
  """Build the Azure Responses model used by this sample."""
  from google.adk.labs.openai import AzureOpenAIResponsesLlm

  endpoint = os.getenv("AZURE_OPENAI_ENDPOINT")
  if not endpoint:
    resource_name = _required_env("AZURE_RESOURCE_NAME")
    endpoint = f"https://{resource_name}.openai.azure.com"
  return AzureOpenAIResponsesLlm(
      model=os.getenv("AZURE_MODEL_DEPLOYMENT", "gpt-4o"),
      api_key=_required_env("AZURE_API_KEY"),
      azure_endpoint=endpoint,
      include_response_metadata=True,
  )


root_agent = Agent(
    name="azure_responses_streaming_agent",
    model=_build_model(),
    description=(
        "Creates Markdown documents while exposing streamed function-call "
        "arguments."
    ),
    instruction=(
        "You are a document planning assistant. When the user asks you to "
        "create, draft, or write a document, you MUST call create_document. "
        "Do not write the full document only in your answer. Build a rich "
        "DocumentRequest with a safe Markdown filename, a clear title, an "
        "executive summary, audience, language, tone, keywords, and three to "
        "six detailed sections. Each section must contain a purpose, body, "
        "multiple key points, and references when useful. After the tool "
        "returns, tell the user where the file was written."
    ),
    tools=[create_document],
)
