# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Utilities for type-safe handling of potentially hallucinated values generated by LLMs."""

from __future__ import annotations

import dataclasses
from typing import cast
from typing import Generic
from typing import TypeVar

from typing_extensions import Literal

_T = TypeVar("_T")


@dataclasses.dataclass(frozen=True)
class MaybeHallucinated(Generic[_T]):
  """A value the model supplied that is not yet confirmed to be valid.

  Attributes:
    maybe_hallucinated_value: The value as the model wrote it.
  """

  maybe_hallucinated_value: _T

  def bounded(self) -> _T | Literal["<hallucinated>"]:
    """Reduces this value to a set of correct values.

    Returns:
      The value itself if it is confirmed to be valid, and the replacement
      value otherwise.
    """
    if isinstance(self, ConfirmedNotHallucinated):
      return cast(_T, self.maybe_hallucinated_value)
    return "<hallucinated>"


@dataclasses.dataclass(frozen=True)
class ConfirmedNotHallucinated(MaybeHallucinated[_T]):
  """A value the model supplied that is confirmed to be valid."""

  @property
  def value(self) -> _T:
    return self.maybe_hallucinated_value
